### ISSUE TITLE
Static files

### ISSUE THREAD

**Issue by codeguru42** [BaseballCardTracker/bbct-api#35]
Serve static and media files from nginx container

**Comment by codeguru42** [comment]
This probably includes a `collectstatic` in django docker image.

**Comment by javidovl** [comment]
In Dockerfile, you do not grant sudo permissions to the new created user, bbct in your case. So, if you want to try `python3 manage.py collectstatic` command, it will probably raise permission error. So, check the #53 , edit the static files folder URL in the places I remarked with comment. Then, give the root permissions to the new user you create in Dockerfile OR collect static files in your local and upload it to the server.

**Comment by codeguru42** [comment]
@javidovl Granting sudo permissions to the user which will run the app is a security hole. I would like to find a different solution.

**Comment by javidovl** [comment]
You can collect static files in your local and upload it to the server, alternatively

**Comment by codeguru42** [comment]
@javidovl That's definitely one option. I can think of a few others. When I have more time, I'll look into this more. If you are still interested in contributing, check out my comments on the PR you submitted. The main thing is that I prefer a separate PR for each issue.
